export const GET_TEMPLATES = "GET_TEMPLATES";
export const GET_TEMPLATES_SUCCESS = "GET_TEMPLATES_SUCCESS";
export const GET_TEMPLATES_ERROR = "GET_TEMPLATES_ERROR";
export const ON_CHANGE_TEMPLATE = "ON_CHANGE_TEMPLATE";

export const GET_HOUSES = "GET_HOUSES";
export const GET_HOUSES_SUCCESS = "GET_HOUSES_SUCCESS";
export const GET_HOUSES_ERROR = "GET_HOUSES_ERROR";